### ISSUE TITLE
Last heading shows up as blue link on the 'On This Page' 

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9448]
https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/user-authorization#see-also 

Adding a video to our slack channel for reference

**Comment by anagio** [comment]
fixed locally set to match colors of other right side links

**Comment by lnhsingh** [comment]
This is still happening for me, just the link is now the same color as the others

![image](https://user-images.githubusercontent.com/15386648/106179015-74dbff80-6168-11eb-9b91-fd5db99c064f.png)

**Comment by anagio** [comment]
@lnhsingh got it I thought it was only the color to fix but I see we want that last item in the TOC's list. There's a bit of JS which sees that See Also heading as an h2 which is higher than the above h3s so it's stopping the list build. If we set that heading to an h3 it'll render in the toc see screenshot just with smaller font size. Is this ok? Or should I work on the JS to accept h2's coming after h3's? Modifying the JS might have side effects if there are nested headings on other pages.
![image](https://user-images.githubusercontent.com/1071553/106229383-09edff80-6220-11eb-8b70-45a12166a2ea.png)
